CFLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

helpingFunctions.o: helpingFunctions.cpp
	g++ $(CFLAGS) -c helpingFunctions.cpp
inputFunctions.o: inputFunctions.cpp
	g++ $(CFLAGS) -c inputFunctions.cpp
solvingFunctions.o: solvingFunctions.cpp
	g++ $(CFLAGS) -c solvingFunctions.cpp
interfaceFunctions.o: interfaceFunctions.cpp
	g++ $(CFLAGS) -c interfaceFunctions.cpp
main.o: main.cpp
	g++ $(CFLAGS) -c main.cpp
testingFunctions.o: testingFunctions.cpp
	g++ $(CFLAGS) -c testingFunctions.cpp
commandLineFunctions.o: commandLineFunctions.cpp
	g++ $(CFLAGS) -c commandLineFunctions.cpp
SolveSquare.exe: helpingFunctions.o inputFunctions.o solvingFunctions.o interfaceFunctions.o main.o testingFunctions.o commandLineFunctions.o
	g++ $(CFLAGS)  helpingFunctions.o inputFunctions.o solvingFunctions.o interfaceFunctions.o main.o testingFunctions.o commandLineFunctions.o -o SolveSquare
clean:
	rm helpingFunctions.o inputFunctions.o solvingFunctions.o interfaceFunctions.o main.o testingFunctions.o commandLineFunctions.o
build: SolveSquare.exe

run: SolveSquare.exe
	./SolveSquare.exe
